/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MlInput {
        "disabled": boolean;
        "name": string;
        "readonly": boolean;
        "type": string;
        "value": string|number;
    }
}
declare global {
    interface HTMLMlInputElement extends Components.MlInput, HTMLStencilElement {
    }
    var HTMLMlInputElement: {
        prototype: HTMLMlInputElement;
        new (): HTMLMlInputElement;
    };
    interface HTMLElementTagNameMap {
        "ml-input": HTMLMlInputElement;
    }
}
declare namespace LocalJSX {
    interface MlInput {
        "disabled"?: boolean;
        "name"?: string;
        "readonly"?: boolean;
        "type"?: string;
        "value"?: string|number;
    }
    interface IntrinsicElements {
        "ml-input": MlInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ml-input": LocalJSX.MlInput & JSXBase.HTMLAttributes<HTMLMlInputElement>;
        }
    }
}
